In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import itertools
import matplotlib.pyplot as plt

In [46]:
match = pd.read_csv("./data/Match.csv")
player_attributes = pd.read_csv("./data/Player_Attributes.csv")
player_attributes.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [47]:
# player_attributes.sample()
required_columns = ["country_id", "league_id", "season", "stage", "date", "match_api_id", "home_team_api_id", 
        "away_team_api_id", "home_team_goal", "away_team_goal", "home_player_1", "home_player_2",
        "home_player_3", "home_player_4", "home_player_5", "home_player_6", "home_player_7", 
        "home_player_8", "home_player_9", "home_player_10", "home_player_11", "away_player_1",
        "away_player_2", "away_player_3", "away_player_4", "away_player_5", "away_player_6",
        "away_player_7", "away_player_8", "away_player_9", "away_player_10", "away_player_11",
        "B365H", "B365D", "B365A", "BWH", "BWD", "BWA"]


match = match[required_columns]
match

,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,...,away_player_8,away_player_9,away_player_10,away_player_11,B365H,B365D,B365A,BWH,BWD,BWA
0,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,...,NaN,NaN,NaN,NaN,1.73,3.40,5.00,1.75,3.35,4.20
1,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,...,NaN,NaN,NaN,NaN,1.95,3.20,3.60,1.80,3.30,3.95
2,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,...,NaN,NaN,NaN,NaN,2.38,3.30,2.75,2.40,3.30,2.55
3,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,...,NaN,NaN,NaN,NaN,1.44,3.75,7.50,1.40,4.00,6.80
4,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,...,NaN,NaN,NaN,NaN,5.00,3.50,1.65,5.00,3.50,1.60
5,1,1,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,1,...,NaN,NaN,NaN,NaN,4.75,3.40,1.67,4.85,3.40,1.65
6,1,1,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,2,...,NaN,NaN,NaN,NaN,2.10,3.20,3.30,2.05,3.25,3.15
7,1,1,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,2,...,NaN,NaN,NaN,NaN,3.20,3.40,2.20,2.55,3.30,2.40
8,1,1,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,0,...,NaN,NaN,NaN,NaN,2.25,3.25,2.88,2.30,3.25,2.70
9,1,1,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,1,...,NaN,NaN,NaN,NaN,1.30,5.25,9.50,1.25,5.00,10.00
10,1,1,2008/2009,10,2008-10-31 00:00:00,492565,9985,9986,1,2,...,NaN,NaN,NaN,NaN,1.30,5.25,9.50,1.25,5.00,10.00
11,1,1,2008/2009,10,2008-11-02 00:00:00,492566,10000,9991,0,2,...,NaN,NaN,NaN,NaN,2.60,3.20,2.50,2.60,3.20,2.40
12,1,1,2008/2009,10,2008-11-01 00:00:00,492567,9994,9998,0,0,...,NaN,NaN,NaN,NaN,1.91,3.40,4.00,1.85,3.35,3.80
13,1,1,2008/2009,10,2008-11-01 00:00:00,492568,7947,10001,2,2,...,NaN,NaN,NaN,NaN,2.90,3.30,2.38,2.75,3.30,2.25
14,1,1,2008/2009,10,2008-11-01 00:00:00,492569,8203,9999,1,2,...,NaN,NaN,NaN,NaN,1.70,3.30,4.50,1.75,3.45,4.00
15,1,1,2008/2009,10,2008-11-01 00:00:00,492570,9996,9984,0,1,...,NaN,NaN,NaN,NaN,2.35,3.30,3.00,2.35,3.25,2.70
16,1,1,2008/2009,10,2008-11-01 00:00:00,492571,4049,9987,1,3,...,NaN,NaN,NaN,NaN,6.00,3.75,1.57,5.10,3.60,1.55
17,1,1,2008/2009,10,2008-11-02 00:00:00,492572,9993,8635,1,3,...,NaN,NaN,NaN,NaN,4.00,3.25,1.83,4.30,3.50,1.68
18,1,1,2008/2009,11,2008-11-08 00:00:00,492573,8635,9994,2,3,...,NaN,NaN,NaN,NaN,1.36,4.75,8.50,1.25,5.00,9.00
19,1,1,2008/2009,11,2008-11-08 00:00:00,492574,9998,9996,0,0,...,NaN,NaN,NaN,NaN,2.40,3.30,2.90,2.25,3.20,2.80
20,1,1,2008/2009,11,2008-11-09 00:00:00,492575,9986,8342,2,2,...,NaN,NaN,NaN,NaN,3.20,3.30,2.25,3.25,3.20,2.10
21,1,1,2008/2009,11,2008-11-07 00:00:00,492576,9984,10000,2,0,...,NaN,NaN,NaN,NaN,1.75,3.75,4.33,1.85,3.35,3.65
22,1,1,2008/2009,11,2008-11-08 00:00:00,492577,9991,7947,1,1,...,NaN,NaN,NaN,NaN,1.40,4.33,8.00,1.38,4.00,7.20
23,1,1,2008/2009,11,2008-11-08 00:00:00,492578,9999,4049,1,2,...,NaN,NaN,NaN,NaN,1.83,3.50,4.20,1.80,3.35,3.90
24,1,1,2008/2009,11,2008-11-08 00:00:00,492579,8571,8203,0,0,...,NaN,NaN,NaN,NaN,2.00,3.50,3.60,1.95,3.25,3.40
25,1,1,2008/2009,11,2008-11-08 00:00:00,492580,10001,9987,1,0,...,NaN,NaN,NaN,NaN,2.70,3.25,2.60,2.50,3.30,2.45
26,1,1,2008/2009,11,2008-11-09 00:00:00,492581,9993,9985,1,3,...,NaN,NaN,NaN,NaN,3.60,3.30,2.05,3.40,3.25,1.95
27,1,1,2008/2009,12,2008-11-16 00:00:00,492582,8342,8635,1,1,...,NaN,NaN,NaN,NaN,2.30,3.25,2.90,2.20,3.15,3.00
28,1,1,2008/2009,12,2008-11-15 00:00:00,492583,9987,9999,1,1,...,NaN,NaN,NaN,NaN,1.25,5.25,10.00,1.23,5.00,10.00
29,1,1,2008/2009,12,2008-11-15 00:00:00,492584,10000,9993,2,2,...,NaN,NaN,NaN,NaN,2.00,3.25,3.50,2.10,3.20,3.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25949,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992066,9956,7896,6,1,...,8893.0,67369.0,491794.0,178142.0,NaN,NaN,NaN,NaN,NaN,NaN
25950,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992067,10199,9931,1,3,...,40274.0,114738.0,41726.0,527103.0,NaN,NaN,NaN,NaN,NaN,NaN
25951,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992068,10190,10243,0,2,...,92252.0,198082.0,540230.0,67306.0,NaN,NaN,NaN,NaN,NaN,NaN
25952,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992069,9824,10179,1,1,...,95230.0,451335.0,106559.0,275122.0,NaN,NaN,NaN,NaN,NaN,NaN
25953,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992070,10192,10191,3,1,...,133126.0,520466.0,184610.0,232110.0,NaN,NaN,NaN,NaN,NaN,NaN
25954,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992071,9931,10191,3,1,...,121115.0,520466.0,232110.0,289732.0,NaN,NaN,NaN,NaN,NaN,NaN
25955,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992072,10192,7896,0,1,...,8893.0,186948.0,93229.0,178142.0,NaN,NaN,NaN,NaN,NaN,NaN
25956,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992073,10199,10190,0,1,...,67333.0,66934.0,176298.0,35831.0,NaN,NaN,NaN,NaN,NaN,NaN
25957,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992074,10179,10243,3,1,...,113235.0,108525.0,254704.0,67306.0,NaN,NaN,NaN,NaN,NaN,NaN
25958,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992075,9824,9956,3,3,...,147959.0,451983.0,80564.0,289472.0,NaN,NaN,NaN,NaN,NaN,NaN
25959,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992076,7896,9931,1,3,...,25794.0,176206.0,402975.0,527104.0,NaN,NaN,NaN,NaN,NaN,NaN
25960,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992077,10179,10192,1,3,...,190525.0,302079.0,45174.0,37554.0,NaN,NaN,NaN,NaN,NaN,NaN
25961,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992078,10190,9956,0,2,...,147959.0,451983.0,80564.0,289472.0,NaN,NaN,NaN,NaN,NaN,NaN
25962,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992079,10191,9824,1,0,...,214344.0,113227.0,114011.0,209371.0,NaN,NaN,NaN,NaN,NaN,NaN
25963,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992080,10243,10199,2,5,...,201704.0,95257.0,104646.0,34082.0,NaN,NaN,NaN,NaN,NaN,NaN
25964,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992081,7896,10199,0,1,...,201704.0,95257.0,104646.0,34082.0,NaN,NaN,NaN,NaN,NaN,NaN
25965,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992082,9824,10190,1,0,...,66934.0,92094.0,195215.0,119839.0,NaN,NaN,NaN,NaN,NaN,NaN
25966,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992083,10191,10179,0,2,...,482200.0,538336.0,95230.0,275122.0,NaN,NaN,NaN,NaN,NaN,NaN
25967,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992084,9931,10243,3,1,...,198082.0,108525.0,194532.0,67306.0,NaN,NaN,NaN,NaN,NaN,NaN
25968,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992085,9956,10192,3,2,...,25860.0,302079.0,45174.0,422412.0,NaN,NaN,NaN,NaN,NaN,NaN
25969,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992086,9931,10190,2,1,...,66934.0,176298.0,92094.0,72628.0,NaN,NaN,NaN,NaN,NaN,NaN
25970,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992087,10192,9824,4,0,...,56868.0,209371.0,531309.0,113227.0,NaN,NaN,NaN,NaN,NaN,NaN
25971,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992088,10199,9956,3,3,...,147959.0,451983.0,80564.0,289472.0,NaN,NaN,NaN,NaN,NaN,NaN
25972,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992089,10243,10191,3,3,...,93223.0,121115.0,25809.0,289732.0,NaN,NaN,NaN,NaN,NaN,NaN
25973,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992090,10179,7896,3,0,...,8893.0,140490.0,93229.0,178142.0,NaN,NaN,NaN,NaN,NaN,NaN
25974,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,...,93223.0,121115.0,232110.0,289732.0,NaN,NaN,NaN,NaN,NaN,NaN
25975,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,...,201704.0,36382.0,34082.0,95257.0,NaN,NaN,NaN,NaN,NaN,NaN
25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,...,482200.0,95230.0,451335.0,275122.0,NaN,NaN,NaN,NaN,NaN,NaN
25977,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,...,462608.0,42262.0,92252.0,194532.0,NaN,NaN,NaN,NaN,NaN,NaN
25978,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,...,40274.0,34035.0,41726.0,527103.0,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
match.dropna(inplace = True)
match

,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,...,away_player_8,away_player_9,away_player_10,away_player_11,B365H,B365D,B365A,BWH,BWD,BWA
145,1,1,2008/2009,24,2009-02-27 00:00:00,493017,8203,9987,2,1,...,9307.0,42153.0,32690.0,38782.0,3.00,3.40,2.30,2.95,3.25,2.20
153,1,1,2008/2009,25,2009-03-08 00:00:00,493025,9984,8342,1,3,...,38336.0,52280.0,27423.0,38440.0,2.80,3.20,2.37,3.10,3.00,2.20
155,1,1,2008/2009,25,2009-03-07 00:00:00,493027,8635,10000,2,0,...,131531.0,130027.0,38231.0,131530.0,1.40,4.50,8.00,1.35,4.00,9.00
162,1,1,2008/2009,26,2009-03-13 00:00:00,493034,8203,8635,2,1,...,38383.0,38393.0,38253.0,37069.0,4.50,3.60,1.75,4.70,3.30,1.70
168,1,1,2008/2009,26,2009-03-14 00:00:00,493040,10000,9999,0,0,...,33671.0,163670.0,37945.0,33622.0,1.75,3.50,4.75,1.60,3.55,5.05
173,1,1,2008/2009,27,2009-03-22 00:00:00,493045,9991,10000,1,0,...,131530.0,130027.0,38231.0,75500.0,1.65,3.60,4.75,1.60,3.40,5.25
176,1,1,2008/2009,27,2009-03-21 00:00:00,493048,9999,8203,1,0,...,67959.0,148286.0,33657.0,26502.0,2.20,3.30,3.00,2.20,3.15,3.00
189,1,1,2008/2009,29,2009-04-12 00:00:00,493061,8635,8342,1,0,...,38336.0,38366.0,27423.0,38440.0,1.67,3.50,5.00,1.67,3.40,4.80
190,1,1,2008/2009,29,2009-04-10 00:00:00,493062,9999,9987,1,0,...,20445.0,32690.0,37202.0,38794.0,3.20,3.25,2.25,3.10,3.30,2.10
219,1,1,2008/2009,31,2009-04-26 00:00:00,493082,9999,9991,1,3,...,32760.0,38229.0,12574.0,46335.0,3.20,3.30,2.10,2.85,3.25,2.20
226,1,1,2008/2009,32,2009-05-02 00:00:00,493089,10000,9985,0,0,...,39591.0,148335.0,37262.0,148315.0,5.50,3.60,1.57,5.50,3.40,1.57
229,1,1,2008/2009,32,2009-05-02 00:00:00,493092,9991,9984,2,1,...,37909.0,104386.0,38251.0,12692.0,1.36,4.33,7.50,1.30,4.50,8.50
231,1,1,2008/2009,32,2009-05-02 00:00:00,493094,10001,9999,1,0,...,163670.0,33622.0,148336.0,94288.0,1.57,3.60,5.50,1.50,3.75,5.55
234,1,1,2008/2009,33,2009-05-09 00:00:00,493097,9985,8342,2,0,...,38336.0,38366.0,38440.0,34025.0,1.44,4.33,7.00,1.45,3.80,6.25
240,1,1,2008/2009,33,2009-05-09 00:00:00,493103,8635,9999,3,1,...,33671.0,163670.0,148336.0,33622.0,1.14,7.50,19.00,1.14,6.20,14.00
242,1,1,2008/2009,33,2009-05-09 00:00:00,493105,9984,10001,2,1,...,17883.0,50160.0,37953.0,30404.0,2.62,3.30,2.62,2.40,3.25,2.60
243,1,1,2008/2009,34,2009-05-16 00:00:00,493106,9987,8635,0,2,...,38253.0,38798.0,38383.0,37069.0,8.00,4.00,1.40,6.50,3.90,1.45
244,1,1,2008/2009,34,2009-05-16 00:00:00,493107,9991,9985,0,1,...,39631.0,39591.0,37262.0,38369.0,4.33,3.80,1.67,4.55,3.60,1.65
308,1,1,2009/2010,1,2009-08-02 00:00:00,665321,9984,9991,1,3,...,26916.0,37065.0,12574.0,46335.0,2.88,3.30,2.25,2.75,3.30,2.25
309,1,1,2009/2010,1,2009-08-01 00:00:00,665322,9994,10000,1,1,...,37981.0,131531.0,75500.0,130027.0,2.30,3.30,2.88,2.05,3.25,3.15
310,1,1,2009/2010,1,2009-08-01 00:00:00,665323,8571,8635,0,2,...,38393.0,38253.0,37069.0,46552.0,5.75,3.60,1.57,5.50,3.50,1.55
313,1,1,2009/2010,10,2009-10-04 00:00:00,665411,8342,8635,4,2,...,38393.0,106013.0,37069.0,12692.0,2.50,3.25,2.60,2.45,3.15,2.65
317,1,1,2009/2010,10,2009-10-03 00:00:00,665417,8203,9994,2,0,...,95609.0,15662.0,34334.0,69629.0,1.91,3.30,4.20,1.90,3.25,3.75
319,1,1,2009/2010,10,2009-10-03 00:00:00,665421,9993,10001,3,1,...,179058.0,182605.0,39848.0,25619.0,1.73,3.50,5.00,1.75,3.50,4.10
320,1,1,2009/2010,11,2009-10-18 00:00:00,665425,8342,9991,1,0,...,32760.0,37065.0,12574.0,46335.0,1.70,3.40,4.75,1.75,3.35,4.15
322,1,1,2009/2010,11,2009-10-18 00:00:00,665427,9987,8203,1,2,...,38969.0,178291.0,17276.0,148286.0,1.85,3.30,4.00,1.95,3.25,3.40
323,1,1,2009/2010,11,2009-10-17 00:00:00,665429,10000,9993,4,0,...,38784.0,38786.0,33622.0,178284.0,1.91,3.30,3.80,1.95,3.25,3.55
324,1,1,2009/2010,11,2009-10-17 00:00:00,665430,9994,9984,1,1,...,38782.0,104386.0,78462.0,38251.0,2.10,3.20,3.30,2.15,3.15,3.15
326,1,1,2009/2010,11,2009-10-17 00:00:00,665435,10001,9985,2,0,...,35412.0,26224.0,148335.0,38369.0,5.50,3.50,1.60,5.50,3.50,1.55
327,1,1,2009/2010,12,2009-10-24 00:00:00,665438,9985,10000,1,1,...,131531.0,38231.0,75500.0,104377.0,1.50,4.00,7.00,1.46,4.00,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24525,21518,21518,2015/2016,6,2015-09-27 00:00:00,2030140,9783,8558,3,0,...,107930.0,52004.0,41622.0,246438.0,2.10,3.30,3.75,2.10,3.25,3.50
24526,21518,21518,2015/2016,6,2015-09-27 00:00:00,2030141,9869,8603,1,2,...,531629.0,37824.0,193226.0,96652.0,2.30,3.20,3.30,2.30,3.10,3.20
24527,21518,21518,2015/2016,7,2015-10-03 00:00:00,2030142,8302,8634,2,1,...,38818.0,522579.0,40636.0,19533.0,4.00,3.60,1.91,4.20,3.50,1.90
24529,21518,21518,2015/2016,7,2015-10-02 00:00:00,2030144,9910,8305,0,0,...,240054.0,369800.0,38573.0,213489.0,1.44,4.50,7.50,1.50,4.10,6.25
24530,21518,21518,2015/2016,7,2015-10-04 00:00:00,2030145,8581,10205,1,0,...,629594.0,268282.0,37506.0,517941.0,4.33,3.40,1.91,4.40,3.50,1.85
24531,21518,21518,2015/2016,7,2015-10-04 00:00:00,2030146,9906,8633,1,1,...,31097.0,191315.0,26166.0,30893.0,3.20,3.30,2.30,3.10,3.10,2.45
24532,21518,21518,2015/2016,7,2015-10-03 00:00:00,2030147,9864,8560,3,1,...,75342.0,150649.0,99047.0,46289.0,2.38,3.10,3.30,2.40,3.10,3.00
24533,21518,21518,2015/2016,7,2015-10-04 00:00:00,2030148,8315,10267,3,1,...,93480.0,361770.0,432463.0,75310.0,2.30,3.30,3.20,2.30,3.40,3.20
24534,21518,21518,2015/2016,7,2015-10-03 00:00:00,2030149,7878,9783,1,1,...,51953.0,198566.0,495107.0,194660.0,2.60,3.20,2.80,2.60,3.00,2.85
24535,21518,21518,2015/2016,7,2015-10-03 00:00:00,2030150,8558,9869,1,2,...,541557.0,395154.0,282689.0,474448.0,2.00,3.30,4.00,2.00,3.20,3.90
24536,21518,21518,2015/2016,7,2015-10-04 00:00:00,2030151,8370,8603,0,2,...,111801.0,193226.0,114746.0,96652.0,2.20,3.50,3.20,2.10,3.40,3.30
24537,21518,21518,2015/2016,8,2015-10-17 00:00:00,2030152,8634,8370,5,2,...,256727.0,36130.0,210065.0,46808.0,1.14,9.00,15.00,1.17,8.25,13.50
24538,21518,21518,2015/2016,8,2015-10-17 00:00:00,2030153,8372,8302,1,1,...,213805.0,111237.0,38821.0,26392.0,3.60,3.40,2.10,3.40,3.30,2.20
24540,21518,21518,2015/2016,8,2015-10-18 00:00:00,2030155,10205,9910,1,2,...,74169.0,49836.0,174472.0,213486.0,2.00,3.50,3.75,2.05,3.40,3.50
24541,21518,21518,2015/2016,8,2015-10-17 00:00:00,2030156,8633,8581,3,0,...,364244.0,513086.0,303088.0,476769.0,1.08,12.00,23.00,1.10,10.50,23.00
24542,21518,21518,2015/2016,8,2015-10-18 00:00:00,2030157,8560,9906,0,2,...,33635.0,184533.0,51360.0,184138.0,4.00,3.20,2.05,3.70,3.25,2.10
24543,21518,21518,2015/2016,8,2015-10-17 00:00:00,2030158,10267,9864,3,0,...,432591.0,37450.0,215927.0,213653.0,1.62,3.75,6.00,1.65,3.80,5.50
24544,21518,21518,2015/2016,8,2015-10-18 00:00:00,2030159,9783,8315,2,2,...,604105.0,33871.0,96619.0,33028.0,2.70,3.10,2.80,2.75,2.95,2.90
24545,21518,21518,2015/2016,8,2015-10-19 00:00:00,2030160,9869,7878,3,3,...,2805.0,80492.0,43372.0,161291.0,2.00,3.20,4.20,2.05,3.20,3.70
24546,21518,21518,2015/2016,8,2015-10-17 00:00:00,2030161,8603,8558,1,3,...,498033.0,52004.0,107930.0,41622.0,2.00,3.30,4.00,2.10,3.20,3.60
24547,21518,21518,2015/2016,9,2015-10-25 00:00:00,2030162,8634,8372,3,1,...,156097.0,187360.0,97762.0,200917.0,1.11,10.00,19.00,1.11,9.50,21.00
24548,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030163,8302,8305,5,0,...,75192.0,240054.0,369800.0,183548.0,1.44,4.33,8.00,1.48,4.33,7.00
24549,21518,21518,2015/2016,9,2015-10-25 00:00:00,2030164,8306,10205,0,0,...,42479.0,562062.0,517941.0,201939.0,3.50,3.25,2.20,3.25,3.25,2.20
24550,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030165,9910,8633,1,3,...,95078.0,359193.0,30893.0,281085.0,3.80,3.80,1.91,3.90,3.90,1.95
24551,21518,21518,2015/2016,9,2015-10-25 00:00:00,2030166,8581,8560,0,4,...,75342.0,33973.0,99047.0,46289.0,2.63,3.20,2.80,2.70,3.00,2.75
24552,21518,21518,2015/2016,9,2015-10-25 00:00:00,2030167,9906,10267,2,1,...,570432.0,361770.0,193869.0,428947.0,1.57,3.80,6.50,1.57,4.00,6.50
24553,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030168,9864,9783,2,0,...,40668.0,474680.0,37653.0,194660.0,2.25,3.25,3.40,2.35,3.10,3.10
24554,21518,21518,2015/2016,9,2015-10-26 00:00:00,2030169,8315,9869,3,0,...,242477.0,541557.0,395154.0,206301.0,1.53,4.00,7.00,1.55,4.00,6.50
24555,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030170,7878,8603,1,1,...,535600.0,193226.0,114746.0,96652.0,2.30,3.25,3.25,2.35,3.25,3.00
24556,21518,21518,2015/2016,9,2015-10-23 00:00:00,2030171,8370,8558,3,0,...,88986.0,498033.0,52004.0,41622.0,2.20,3.40,3.20,2.25,3.50,3.20

In [49]:
winner_condition = [match["home_team_goal"] > match["away_team_goal"],
                    match["home_team_goal"] < match["away_team_goal"],
                    match["home_team_goal"] == match["away_team_goal"],
                    ]
winner = [match["home_team_api_id"], match["away_team_api_id"], -1]

match["Winner"] = np.select(winner_condition, winner)
match

,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,...,away_player_9,away_player_10,away_player_11,B365H,B365D,B365A,BWH,BWD,BWA,Winner
145,1,1,2008/2009,24,2009-02-27 00:00:00,493017,8203,9987,2,1,...,42153.0,32690.0,38782.0,3.00,3.40,2.30,2.95,3.25,2.20,8203
153,1,1,2008/2009,25,2009-03-08 00:00:00,493025,9984,8342,1,3,...,52280.0,27423.0,38440.0,2.80,3.20,2.37,3.10,3.00,2.20,8342
155,1,1,2008/2009,25,2009-03-07 00:00:00,493027,8635,10000,2,0,...,130027.0,38231.0,131530.0,1.40,4.50,8.00,1.35,4.00,9.00,8635
162,1,1,2008/2009,26,2009-03-13 00:00:00,493034,8203,8635,2,1,...,38393.0,38253.0,37069.0,4.50,3.60,1.75,4.70,3.30,1.70,8203
168,1,1,2008/2009,26,2009-03-14 00:00:00,493040,10000,9999,0,0,...,163670.0,37945.0,33622.0,1.75,3.50,4.75,1.60,3.55,5.05,-1
173,1,1,2008/2009,27,2009-03-22 00:00:00,493045,9991,10000,1,0,...,130027.0,38231.0,75500.0,1.65,3.60,4.75,1.60,3.40,5.25,9991
176,1,1,2008/2009,27,2009-03-21 00:00:00,493048,9999,8203,1,0,...,148286.0,33657.0,26502.0,2.20,3.30,3.00,2.20,3.15,3.00,9999
189,1,1,2008/2009,29,2009-04-12 00:00:00,493061,8635,8342,1,0,...,38366.0,27423.0,38440.0,1.67,3.50,5.00,1.67,3.40,4.80,8635
190,1,1,2008/2009,29,2009-04-10 00:00:00,493062,9999,9987,1,0,...,32690.0,37202.0,38794.0,3.20,3.25,2.25,3.10,3.30,2.10,9999
219,1,1,2008/2009,31,2009-04-26 00:00:00,493082,9999,9991,1,3,...,38229.0,12574.0,46335.0,3.20,3.30,2.10,2.85,3.25,2.20,9991
226,1,1,2008/2009,32,2009-05-02 00:00:00,493089,10000,9985,0,0,...,148335.0,37262.0,148315.0,5.50,3.60,1.57,5.50,3.40,1.57,-1
229,1,1,2008/2009,32,2009-05-02 00:00:00,493092,9991,9984,2,1,...,104386.0,38251.0,12692.0,1.36,4.33,7.50,1.30,4.50,8.50,9991
231,1,1,2008/2009,32,2009-05-02 00:00:00,493094,10001,9999,1,0,...,33622.0,148336.0,94288.0,1.57,3.60,5.50,1.50,3.75,5.55,10001
234,1,1,2008/2009,33,2009-05-09 00:00:00,493097,9985,8342,2,0,...,38366.0,38440.0,34025.0,1.44,4.33,7.00,1.45,3.80,6.25,9985
240,1,1,2008/2009,33,2009-05-09 00:00:00,493103,8635,9999,3,1,...,163670.0,148336.0,33622.0,1.14,7.50,19.00,1.14,6.20,14.00,8635
242,1,1,2008/2009,33,2009-05-09 00:00:00,493105,9984,10001,2,1,...,50160.0,37953.0,30404.0,2.62,3.30,2.62,2.40,3.25,2.60,9984
243,1,1,2008/2009,34,2009-05-16 00:00:00,493106,9987,8635,0,2,...,38798.0,38383.0,37069.0,8.00,4.00,1.40,6.50,3.90,1.45,8635
244,1,1,2008/2009,34,2009-05-16 00:00:00,493107,9991,9985,0,1,...,39591.0,37262.0,38369.0,4.33,3.80,1.67,4.55,3.60,1.65,9985
308,1,1,2009/2010,1,2009-08-02 00:00:00,665321,9984,9991,1,3,...,37065.0,12574.0,46335.0,2.88,3.30,2.25,2.75,3.30,2.25,9991
309,1,1,2009/2010,1,2009-08-01 00:00:00,665322,9994,10000,1,1,...,131531.0,75500.0,130027.0,2.30,3.30,2.88,2.05,3.25,3.15,-1
310,1,1,2009/2010,1,2009-08-01 00:00:00,665323,8571,8635,0,2,...,38253.0,37069.0,46552.0,5.75,3.60,1.57,5.50,3.50,1.55,8635
313,1,1,2009/2010,10,2009-10-04 00:00:00,665411,8342,8635,4,2,...,106013.0,37069.0,12692.0,2.50,3.25,2.60,2.45,3.15,2.65,8342
317,1,1,2009/2010,10,2009-10-03 00:00:00,665417,8203,9994,2,0,...,15662.0,34334.0,69629.0,1.91,3.30,4.20,1.90,3.25,3.75,8203
319,1,1,2009/2010,10,2009-10-03 00:00:00,665421,9993,10001,3,1,...,182605.0,39848.0,25619.0,1.73,3.50,5.00,1.75,3.50,4.10,9993
320,1,1,2009/2010,11,2009-10-18 00:00:00,665425,8342,9991,1,0,...,37065.0,12574.0,46335.0,1.70,3.40,4.75,1.75,3.35,4.15,8342
322,1,1,2009/2010,11,2009-10-18 00:00:00,665427,9987,8203,1,2,...,178291.0,17276.0,148286.0,1.85,3.30,4.00,1.95,3.25,3.40,8203
323,1,1,2009/2010,11,2009-10-17 00:00:00,665429,10000,9993,4,0,...,38786.0,33622.0,178284.0,1.91,3.30,3.80,1.95,3.25,3.55,10000
324,1,1,2009/2010,11,2009-10-17 00:00:00,665430,9994,9984,1,1,...,104386.0,78462.0,38251.0,2.10,3.20,3.30,2.15,3.15,3.15,-1
326,1,1,2009/2010,11,2009-10-17 00:00:00,665435,10001,9985,2,0,...,26224.0,148335.0,38369.0,5.50,3.50,1.60,5.50,3.50,1.55,10001
327,1,1,2009/2010,12,2009-10-24 00:00:00,665438,9985,10000,1,1,...,38231.0,75500.0,104377.0,1.50,4.00,7.00,1.46,4.00,6.00,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24525,21518,21518,2015/2016,6,2015-09-27 00:00:00,2030140,9783,8558,3,0,...,52004.0,41622.0,246438.0,2.10,3.30,3.75,2.10,3.25,3.50,9783
24526,21518,21518,2015/2016,6,2015-09-27 00:00:00,2030141,9869,8603,1,2,...,37824.0,193226.0,96652.0,2.30,3.20,3.30,2.30,3.10,3.20,8603
24527,21518,21518,2015/2016,7,2015-10-03 00:00:00,2030142,8302,8634,2,1,...,522579.0,40636.0,19533.0,4.00,3.60,1.91,4.20,3.50,1.90,8302
24529,21518,21518,2015/2016,7,2015-10-02 00:00:00,2030144,9910,8305,0,0,...,369800.0,38573.0,213489.0,1.44,4.50,7.50,1.50,4.10,6.25,-1
24530,21518,21518,2015/2016,7,2015-10-04 00:00:00,2030145,8581,10205,1,0,...,268282.0,37506.0,517941.0,4.33,3.40,1.91,4.40,3.50,1.85,8581
24531,21518,21518,2015/2016,7,2015-10-04 00:00:00,2030146,9906,8633,1,1,...,191315.0,26166.0,30893.0,3.20,3.30,2.30,3.10,3.10,2.45,-1
24532,21518,21518,2015/2016,7,2015-10-03 00:00:00,2030147,9864,8560,3,1,...,150649.0,99047.0,46289.0,2.38,3.10,3.30,2.40,3.10,3.00,9864
24533,21518,21518,2015/2016,7,2015-10-04 00:00:00,2030148,8315,10267,3,1,...,361770.0,432463.0,75310.0,2.30,3.30,3.20,2.30,3.40,3.20,8315
24534,21518,21518,2015/2016,7,2015-10-03 00:00:00,2030149,7878,9783,1,1,...,198566.0,495107.0,194660.0,2.60,3.20,2.80,2.60,3.00,2.85,-1
24535,21518,21518,2015/2016,7,2015-10-03 00:00:00,2030150,8558,9869,1,2,...,395154.0,282689.0,474448.0,2.00,3.30,4.00,2.00,3.20,3.90,9869
24536,21518,21518,2015/2016,7,2015-10-04 00:00:00,2030151,8370,8603,0,2,...,193226.0,114746.0,96652.0,2.20,3.50,3.20,2.10,3.40,3.30,8603
24537,21518,21518,2015/2016,8,2015-10-17 00:00:00,2030152,8634,8370,5,2,...,36130.0,210065.0,46808.0,1.14,9.00,15.00,1.17,8.25,13.50,8634
24538,21518,21518,2015/2016,8,2015-10-17 00:00:00,2030153,8372,8302,1,1,...,111237.0,38821.0,26392.0,3.60,3.40,2.10,3.40,3.30,2.20,-1
24540,21518,21518,2015/2016,8,2015-10-18 00:00:00,2030155,10205,9910,1,2,...,49836.0,174472.0,213486.0,2.00,3.50,3.75,2.05,3.40,3.50,9910
24541,21518,21518,2015/2016,8,2015-10-17 00:00:00,2030156,8633,8581,3,0,...,513086.0,303088.0,476769.0,1.08,12.00,23.00,1.10,10.50,23.00,8633
24542,21518,21518,2015/2016,8,2015-10-18 00:00:00,2030157,8560,9906,0,2,...,184533.0,51360.0,184138.0,4.00,3.20,2.05,3.70,3.25,2.10,9906
24543,21518,21518,2015/2016,8,2015-10-17 00:00:00,2030158,10267,9864,3,0,...,37450.0,215927.0,213653.0,1.62,3.75,6.00,1.65,3.80,5.50,10267
24544,21518,21518,2015/2016,8,2015-10-18 00:00:00,2030159,9783,8315,2,2,...,33871.0,96619.0,33028.0,2.70,3.10,2.80,2.75,2.95,2.90,-1
24545,21518,21518,2015/2016,8,2015-10-19 00:00:00,2030160,9869,7878,3,3,...,80492.0,43372.0,161291.0,2.00,3.20,4.20,2.05,3.20,3.70,-1
24546,21518,21518,2015/2016,8,2015-10-17 00:00:00,2030161,8603,8558,1,3,...,52004.0,107930.0,41622.0,2.00,3.30,4.00,2.10,3.20,3.60,8558
24547,21518,21518,2015/2016,9,2015-10-25 00:00:00,2030162,8634,8372,3,1,...,187360.0,97762.0,200917.0,1.11,10.00,19.00,1.11,9.50,21.00,8634
24548,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030163,8302,8305,5,0,...,240054.0,369800.0,183548.0,1.44,4.33,8.00,1.48,4.33,7.00,8302
24549,21518,21518,2015/2016,9,2015-10-25 00:00:00,2030164,8306,10205,0,0,...,562062.0,517941.0,201939.0,3.50,3.25,2.20,3.25,3.25,2.20,-1
24550,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030165,9910,8633,1,3,...,359193.0,30893.0,281085.0,3.80,3.80,1.91,3.90,3.90,1.95,8633
24551,21518,21518,2015/2016,9,2015-10-25 00:00:00,2030166,8581,8560,0,4,...,33973.0,99047.0,46289.0,2.63,3.20,2.80,2.70,3.00,2.75,8560
24552,21518,21518,2015/2016,9,2015-10-25 00:00:00,2030167,9906,10267,2,1,...,361770.0,193869.0,428947.0,1.57,3.80,6.50,1.57,4.00,6.50,9906
24553,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030168,9864,9783,2,0,...,474680.0,37653.0,194660.0,2.25,3.25,3.40,2.35,3.10,3.10,9864
24554,21518,21518,2015/2016,9,2015-10-26 00:00:00,2030169,8315,9869,3,0,...,541557.0,395154.0,206301.0,1.53,4.00,7.00,1.55,4.00,6.50,8315
24555,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030170,7878,8603,1,1,...,193226.0,114746.0,96652.0,2.30,3.25,3.25,2.35,3.25,3.00,-1
24556,21518,21518,2015/2016,9,2015-10-23 00:00:00,2030171,8370,8558,3,0,...,498033.0,52004.0,41622.0,2.20,3.40,3.20,2.25,3.50,3.20,8370

In [30]:
player_id = match_instance["home_player_2"]
attr = player_attributes[player_attributes.player_api_id == player_id]
attr.sort_values(by = 'date', ascending = False)[:1]
attr.reset_index(inplace= True, drop = True)
attr
overall_rating = pd.Series(attr.loc[0, "overall_rating"])
overall_rating

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,95024,155835,67950,2014-07-18 00:00:00,65.0,65.0,right,low,high,47.0,...,59.0,25.0,68.0,68.0,66.0,7.0,7.0,9.0,10.0,15.0
1,95025,155835,67950,2014-03-07 00:00:00,65.0,65.0,right,low,high,47.0,...,59.0,25.0,68.0,68.0,66.0,7.0,7.0,9.0,10.0,15.0
2,95026,155835,67950,2014-02-14 00:00:00,65.0,65.0,right,low,high,47.0,...,59.0,25.0,68.0,68.0,66.0,7.0,7.0,9.0,10.0,15.0
3,95027,155835,67950,2013-09-20 00:00:00,65.0,65.0,right,low,high,47.0,...,59.0,25.0,68.0,68.0,66.0,7.0,7.0,9.0,10.0,15.0
4,95028,155835,67950,2013-02-15 00:00:00,65.0,67.0,right,low,high,47.0,...,59.0,25.0,68.0,68.0,66.0,7.0,7.0,9.0,10.0,15.0
5,95029,155835,67950,2012-08-31 00:00:00,67.0,67.0,right,low,high,47.0,...,59.0,25.0,68.0,68.0,66.0,7.0,7.0,9.0,10.0,15.0
6,95030,155835,67950,2012-02-22 00:00:00,65.0,66.0,right,medium,medium,47.0,...,59.0,25.0,68.0,66.0,65.0,7.0,7.0,9.0,10.0,15.0
7,95031,155835,67950,2011-08-30 00:00:00,65.0,65.0,right,medium,medium,47.0,...,59.0,25.0,68.0,66.0,65.0,7.0,7.0,9.0,10.0,15.0
8,95032,155835,67950,2010-08-30 00:00:00,65.0,68.0,right,medium,medium,47.0,...,59.0,25.0,68.0,66.0,65.0,7.0,7.0,9.0,10.0,15.0
9,95033,155835,67950,2010-02-22 00:00:00,62.0,63.0,right,medium,medium,47.0,...,59.0,54.0,66.0,61.0,65.0,9.0,20.0,45.0,20.0,20.0
10,95034,155835,67950,2009-08-30 00:00:00,60.0,63.0,right,medium,medium,47.0,...,59.0,54.0,66.0,59.0,65.0,9.0,20.0,45.0,20.0,20.0
11,95035,155835,67950,2009-02-22 00:00:00,57.0,59.0,right,medium,medium,37.0,...,59.0,52.0,66.0,57.0,65.0,13.0,20.0,35.0,20.0,20.0
12,95036,155835,67950,2008-08-30 00:00:00,57.0,59.0,right,medium,medium,37.0,...,59.0,52.0,66.0,57.0,65.0,13.0,20.0,35.0,20.0,20.0
13,95037,155835,67950,2007-08-30 00:00:00,59.0,59.0,right,medium,medium,37.0,...,59.0,52.0,66.0,57.0,65.0,13.0,20.0,35.0,20.0,20.0
14,95038,155835,67950,2007-02-22 00:00:00,59.0,59.0,right,medium,medium,37.0,...,59.0,52.0,66.0,57.0,65.0,13.0,20.0,35.0,20.0,20.0

In [67]:
def match_player_attributes(match_instance, player_attributes, players):
    match_id =  match_instance.match_api_id
    date = match_instance['date']
    
    player_attr_instance = pd.DataFrame() #new df
    player_rating =[]
    for player in players:
        player_id = match_instance[player]
        attr = player_attributes[player_attributes.player_api_id == player_id]
    
        attr_tilldate = attr[attr.date < date].sort_values(by = 'date', ascending = False)[:1]
        attr_tilldate.reset_index(inplace = True, drop = True)
        overall_rating = pd.Series(attr_tilldate.loc[0, "overall_rating"])
    
        rating = "{}_overall_rating".format(player)
        player_rating.append(rating)
        player_attr_instance = pd.concat([player_attr_instance, overall_rating], axis = 1)

    
    player_attr_instance.columns = player_rating        
    player_attr_instance['match_api_id'] = match_id

    player_attr_instance.reset_index(inplace = True, drop = True)
    return player_attr_instance.loc[0]

In [68]:
players = ['home_player_1', 'home_player_2', 'home_player_3', "home_player_4", "home_player_5",
            "home_player_6", "home_player_7", "home_player_8", "home_player_9", "home_player_10",
            "home_player_11", "away_player_1", "away_player_2", "away_player_3", "away_player_4",
            "away_player_5", "away_player_6", "away_player_7", "away_player_8", "away_player_9",
            "away_player_10", "away_player_11"]

def merge_player_attributes(match_table, player_attributes_table):
    merged_tables = match_table.apply(lambda x: match_player_attributes(x, player_attributes, players), axis = 1)
    return merged_tables

xy = merge_player_attributes(match, player_attributes)
xy

,home_player_1_overall_rating,home_player_2_overall_rating,home_player_3_overall_rating,home_player_4_overall_rating,home_player_5_overall_rating,home_player_6_overall_rating,home_player_7_overall_rating,home_player_8_overall_rating,home_player_9_overall_rating,home_player_10_overall_rating,...,away_player_3_overall_rating,away_player_4_overall_rating,away_player_5_overall_rating,away_player_6_overall_rating,away_player_7_overall_rating,away_player_8_overall_rating,away_player_9_overall_rating,away_player_10_overall_rating,away_player_11_overall_rating,match_api_id
145,58.0,57.0,67.0,53.0,60.0,63.0,60.0,66.0,50.0,65.0,...,59.0,55.0,54.0,72.0,67.0,65.0,70.0,68.0,63.0,493017.0
153,64.0,64.0,63.0,62.0,62.0,72.0,68.0,67.0,69.0,68.0,...,66.0,67.0,66.0,70.0,69.0,68.0,67.0,73.0,68.0,493025.0
155,67.0,72.0,69.0,69.0,72.0,75.0,74.0,70.0,74.0,64.0,...,61.0,60.0,49.0,64.0,67.0,66.0,55.0,58.0,64.0,493027.0
162,58.0,57.0,67.0,65.0,66.0,60.0,53.0,60.0,50.0,64.0,...,72.0,66.0,67.0,75.0,70.0,74.0,74.0,70.0,69.0,493034.0
168,61.0,66.0,61.0,61.0,60.0,64.0,67.0,66.0,64.0,58.0,...,57.0,57.0,51.0,58.0,66.0,57.0,60.0,63.0,65.0,493040.0
173,66.0,69.0,64.0,63.0,63.0,69.0,64.0,69.0,71.0,67.0,...,66.0,61.0,49.0,67.0,66.0,64.0,55.0,58.0,56.0,493045.0
176,64.0,62.0,57.0,57.0,51.0,66.0,57.0,60.0,56.0,63.0,...,57.0,67.0,50.0,66.0,60.0,53.0,60.0,64.0,58.0,493048.0
189,67.0,72.0,72.0,69.0,72.0,71.0,75.0,74.0,74.0,70.0,...,67.0,66.0,67.0,70.0,71.0,68.0,66.0,73.0,68.0,493061.0
190,64.0,59.0,57.0,57.0,51.0,66.0,57.0,60.0,56.0,63.0,...,70.0,55.0,54.0,63.0,67.0,63.0,68.0,72.0,63.0,493062.0
219,64.0,59.0,57.0,57.0,51.0,58.0,66.0,57.0,60.0,65.0,...,63.0,65.0,63.0,69.0,64.0,69.0,71.0,66.0,68.0,493082.0
226,61.0,66.0,61.0,61.0,60.0,67.0,66.0,49.0,55.0,65.0,...,75.0,64.0,71.0,71.0,76.0,75.0,54.0,76.0,56.0,493089.0
229,66.0,69.0,67.0,63.0,65.0,69.0,64.0,69.0,71.0,61.0,...,62.0,62.0,63.0,66.0,68.0,67.0,62.0,67.0,64.0,493092.0
231,64.0,65.0,56.0,63.0,59.0,64.0,70.0,64.0,63.0,63.0,...,62.0,57.0,66.0,57.0,51.0,60.0,65.0,56.0,57.0,493094.0
234,63.0,75.0,64.0,65.0,71.0,71.0,76.0,75.0,54.0,76.0,...,64.0,66.0,66.0,70.0,71.0,68.0,66.0,68.0,65.0,493097.0
240,67.0,72.0,72.0,69.0,72.0,71.0,70.0,74.0,74.0,57.0,...,63.0,62.0,51.0,58.0,66.0,57.0,60.0,56.0,65.0,493103.0
242,50.0,64.0,62.0,62.0,63.0,68.0,67.0,62.0,69.0,68.0,...,59.0,64.0,64.0,56.0,63.0,63.0,62.0,63.0,70.0,493105.0
243,62.0,69.0,66.0,70.0,59.0,65.0,67.0,55.0,68.0,62.0,...,72.0,69.0,72.0,75.0,74.0,70.0,71.0,74.0,69.0,493106.0
244,66.0,67.0,63.0,65.0,63.0,69.0,64.0,69.0,71.0,66.0,...,64.0,65.0,59.0,71.0,65.0,76.0,75.0,76.0,74.0,493107.0
308,64.0,64.0,64.0,63.0,62.0,68.0,67.0,62.0,65.0,67.0,...,63.0,65.0,63.0,69.0,64.0,61.0,68.0,66.0,68.0,665321.0
309,68.0,66.0,66.0,66.0,59.0,65.0,68.0,58.0,63.0,68.0,...,61.0,60.0,49.0,65.0,66.0,67.0,66.0,56.0,55.0,665322.0
310,64.0,64.0,58.0,57.0,58.0,60.0,66.0,57.0,66.0,63.0,...,72.0,69.0,72.0,70.0,74.0,74.0,70.0,69.0,68.0,665323.0
313,73.0,69.0,67.0,68.0,63.0,67.0,71.0,68.0,67.0,72.0,...,70.0,73.0,70.0,70.0,77.0,74.0,61.0,73.0,66.0,665411.0
317,70.0,60.0,65.0,62.0,55.0,66.0,64.0,62.0,65.0,64.0,...,66.0,66.0,64.0,68.0,64.0,64.0,69.0,66.0,67.0,665417.0
319,64.0,68.0,64.0,66.0,64.0,69.0,72.0,64.0,68.0,69.0,...,68.0,63.0,63.0,63.0,64.0,60.0,59.0,63.0,64.0,665421.0
320,73.0,69.0,67.0,67.0,68.0,69.0,71.0,68.0,67.0,68.0,...,69.0,69.0,65.0,69.0,65.0,71.0,68.0,70.0,69.0,665425.0
322,64.0,70.0,62.0,63.0,63.0,70.0,69.0,68.0,67.0,70.0,...,65.0,58.0,55.0,66.0,64.0,62.0,65.0,67.0,64.0,665427.0
323,67.0,67.0,64.0,63.0,64.0,65.0,69.0,71.0,65.0,63.0,...,64.0,66.0,64.0,69.0,72.0,64.0,68.0,69.0,56.0,665429.0
324,73.0,67.0,67.0,66.0,64.0,68.0,64.0,69.0,68.0,67.0,...,64.0,67.0,65.0,70.0,68.0,64.0,66.0,66.0,65.0,665430.0
326,67.0,65.0,63.0,64.0,64.0,63.0,65.0,63.0,59.0,63.0,...,67.0,73.0,66.0,76.0,76.0,74.0,68.0,65.0,77.0,665435.0
327,63.0,73.0,74.0,66.0,73.0,76.0,76.0,68.0,65.0,67.0,...,63.0,64.0,63.0,65.0,69.0,71.0,65.0,63.0,63.0,665438.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24525,76.0,74.0,72.0,77.0,76.0,77.0,75.0,73.0,76.0,78.0,...,76.0,74.0,71.0,75.0,77.0,76.0,73.0,78.0,75.0,2030140.0
24526,70.0,74.0,71.0,76.0,72.0,75.0,74.0,76.0,68.0,76.0,...,76.0,73.0,71.0,74.0,75.0,74.0,79.0,75.0,79.0,2030141.0
24527,74.0,80.0,77.0,74.0,81.0,82.0,79.0,79.0,81.0,81.0,...,85.0,83.0,84.0,84.0,86.0,83.0,73.0,90.0,88.0,2030142.0
24529,76.0,78.0,77.0,73.0,76.0,77.0,77.0,77.0,79.0,78.0,...,74.0,76.0,70.0,74.0,72.0,77.0,76.0,74.0,74.0,2030144.0
24530,75.0,75.0,75.0,74.0,73.0,74.0,72.0,77.0,71.0,76.0,...,73.0,80.0,76.0,78.0,78.0,67.0,79.0,79.0,68.0,2030145.0
24531,81.0,81.0,78.0,85.0,82.0,79.0,80.0,81.0,77.0,79.0,...,82.0,87.0,83.0,87.0,77.0,87.0,84.0,86.0,93.0,2030146.0
24532,78.0,75.0,76.0,78.0,75.0,75.0,76.0,73.0,72.0,73.0,...,75.0,80.0,78.0,79.0,77.0,82.0,79.0,75.0,76.0,2030147.0
24533,79.0,80.0,77.0,83.0,79.0,80.0,80.0,74.0,81.0,78.0,...,76.0,82.0,76.0,80.0,82.0,81.0,80.0,73.0,81.0,2030148.0
24534,77.0,76.0,74.0,75.0,73.0,75.0,75.0,73.0,74.0,73.0,...,75.0,77.0,76.0,75.0,76.0,77.0,73.0,74.0,78.0,2030149.0
24535,70.0,73.0,76.0,75.0,71.0,77.0,76.0,74.0,75.0,73.0,...,74.0,76.0,72.0,74.0,75.0,77.0,77.0,68.0,72.0,2030150.0
24536,75.0,75.0,76.0,71.0,76.0,78.0,80.0,73.0,71.0,72.0,...,72.0,76.0,71.0,74.0,72.0,75.0,75.0,72.0,79.0,2030151.0
24537,83.0,84.0,85.0,83.0,84.0,78.0,86.0,84.0,72.0,90.0,...,76.0,70.0,76.0,71.0,80.0,77.0,75.0,72.0,73.0,2030152.0
24538,71.0,73.0,74.0,72.0,70.0,71.0,74.0,73.0,74.0,75.0,...,79.0,74.0,81.0,82.0,79.0,81.0,81.0,79.0,79.0,2030153.0
24540,76.0,79.0,73.0,80.0,77.0,78.0,79.0,78.0,69.0,78.0,...,77.0,73.0,76.0,77.0,79.0,77.0,79.0,78.0,82.0,2030155.0
24541,79.0,81.0,82.0,75.0,83.0,78.0,87.0,77.0,87.0,93.0,...,75.0,74.0,73.0,74.0,75.0,72.0,75.0,71.0,76.0,2030156.0
24542,79.0,72.0,75.0,80.0,78.0,76.0,79.0,82.0,79.0,75.0,...,79.0,85.0,82.0,77.0,81.0,80.0,83.0,84.0,83.0,2030157.0
24543,72.0,73.0,82.0,80.0,80.0,80.0,80.0,75.0,82.0,80.0,...,76.0,78.0,74.0,64.0,81.0,74.0,73.0,72.0,75.0,2030158.0
24544,76.0,74.0,75.0,77.0,75.0,73.0,76.0,75.0,75.0,73.0,...,77.0,83.0,79.0,80.0,80.0,74.0,81.0,78.0,82.0,2030159.0
24545,70.0,76.0,74.0,76.0,72.0,75.0,73.0,76.0,77.0,70.0,...,74.0,75.0,73.0,75.0,70.0,76.0,74.0,73.0,75.0,2030160.0
24546,77.0,73.0,76.0,71.0,72.0,71.0,75.0,79.0,75.0,74.0,...,76.0,75.0,71.0,77.0,74.0,75.0,73.0,76.0,78.0,2030161.0
24547,83.0,84.0,80.0,85.0,84.0,83.0,86.0,84.0,72.0,90.0,...,73.0,72.0,70.0,71.0,74.0,72.0,74.0,74.0,72.0,2030162.0
24548,75.0,77.0,79.0,74.0,81.0,82.0,81.0,81.0,81.0,82.0,...,73.0,75.0,74.0,76.0,74.0,78.0,77.0,76.0,71.0,2030163.0
24549,75.0,73.0,72.0,71.0,72.0,71.0,69.0,74.0,67.0,76.0,...,77.0,80.0,77.0,78.0,78.0,81.0,77.0,70.0,76.0,2030164.0
24550,76.0,78.0,77.0,73.0,76.0,77.0,79.0,77.0,80.0,78.0,...,87.0,82.0,83.0,87.0,77.0,87.0,76.0,93.0,78.0,2030165.0
24551,75.0,77.0,75.0,75.0,73.0,74.0,75.0,72.0,72.0,71.0,...,76.0,80.0,71.0,76.0,79.0,82.0,77.0,75.0,76.0,2030166.0
24552,81.0,81.0,79.0,85.0,82.0,80.0,81.0,83.0,78.0,84.0,...,82.0,80.0,80.0,82.0,79.0,77.0,80.0,79.0,75.0,2030167.0
24553,79.0,75.0,74.0,78.0,76.0,75.0,76.0,74.0,73.0,72.0,...,75.0,77.0,75.0,75.0,77.0,76.0,74.0,73.0,78.0,2030168.0
24554,79.0,80.0,77.0,83.0,79.0,80.0,81.0,80.0,74.0,78.0,...,74.0,76.0,73.0,71.0,75.0,73.0,76.0,77.0,72.0,2030169.0
24555,77.0,71.0,74.0,72.0,73.0,76.0,75.0,74.0,70.0,75.0,...,72.0,76.0,71.0,79.0,75.0,71.0,75.0,72.0,79.0,2030170.0
24556,75.0,77.0,76.0,70.0,76.0,78.0,80.0,77.0,71.0,75.0,...,75.0,76.0,71.0,76.0,77.0,74.0,75.0,73.0,78.0,2030171.0

In [70]:
xy["match_api_id"] = xy["match_api_id"].astype(int)
xy.head()

,home_player_1_overall_rating,home_player_2_overall_rating,home_player_3_overall_rating,home_player_4_overall_rating,home_player_5_overall_rating,home_player_6_overall_rating,home_player_7_overall_rating,home_player_8_overall_rating,home_player_9_overall_rating,home_player_10_overall_rating,...,away_player_3_overall_rating,away_player_4_overall_rating,away_player_5_overall_rating,away_player_6_overall_rating,away_player_7_overall_rating,away_player_8_overall_rating,away_player_9_overall_rating,away_player_10_overall_rating,away_player_11_overall_rating,match_api_id
145,58.0,57.0,67.0,53.0,60.0,63.0,60.0,66.0,50.0,65.0,...,59.0,55.0,54.0,72.0,67.0,65.0,70.0,68.0,63.0,493017
153,64.0,64.0,63.0,62.0,62.0,72.0,68.0,67.0,69.0,68.0,...,66.0,67.0,66.0,70.0,69.0,68.0,67.0,73.0,68.0,493025
155,67.0,72.0,69.0,69.0,72.0,75.0,74.0,70.0,74.0,64.0,...,61.0,60.0,49.0,64.0,67.0,66.0,55.0,58.0,64.0,493027
162,58.0,57.0,67.0,65.0,66.0,60.0,53.0,60.0,50.0,64.0,...,72.0,66.0,67.0,75.0,70.0,74.0,74.0,70.0,69.0,493034
168,61.0,66.0,61.0,61.0,60.0,64.0,67.0,66.0,64.0,58.0,...,57.0,57.0,51.0,58.0,66.0,57.0,60.0,63.0,65.0,493040

In [71]:
joined_df = match.merge(xy, on="match_api_id")
joined_df.head()

,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,...,away_player_2_overall_rating,away_player_3_overall_rating,away_player_4_overall_rating,away_player_5_overall_rating,away_player_6_overall_rating,away_player_7_overall_rating,away_player_8_overall_rating,away_player_9_overall_rating,away_player_10_overall_rating,away_player_11_overall_rating
0,1,1,2008/2009,24,2009-02-27 00:00:00,493017,8203,9987,2,1,...,70.0,59.0,55.0,54.0,72.0,67.0,65.0,70.0,68.0,63.0
1,1,1,2008/2009,25,2009-03-08 00:00:00,493025,9984,8342,1,3,...,67.0,66.0,67.0,66.0,70.0,69.0,68.0,67.0,73.0,68.0
2,1,1,2008/2009,25,2009-03-07 00:00:00,493027,8635,10000,2,0,...,66.0,61.0,60.0,49.0,64.0,67.0,66.0,55.0,58.0,64.0
3,1,1,2008/2009,26,2009-03-13 00:00:00,493034,8203,8635,2,1,...,72.0,72.0,66.0,67.0,75.0,70.0,74.0,74.0,70.0,69.0
4,1,1,2008/2009,26,2009-03-14 00:00:00,493040,10000,9999,0,0,...,62.0,57.0,57.0,51.0,58.0,66.0,57.0,60.0,63.0,65.0

In [72]:
winner_condition = [match["home_team_goal"] > match["away_team_goal"],
                    match["home_team_goal"] < match["away_team_goal"],
                    match["home_team_goal"] == match["away_team_goal"],
                    ]
winner = ["Win","Lose", "Draw"]

joined_df["Winner2"] = np.select(winner_condition, winner)
joined_df.head()

,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,...,away_player_3_overall_rating,away_player_4_overall_rating,away_player_5_overall_rating,away_player_6_overall_rating,away_player_7_overall_rating,away_player_8_overall_rating,away_player_9_overall_rating,away_player_10_overall_rating,away_player_11_overall_rating,Winner2
0,1,1,2008/2009,24,2009-02-27 00:00:00,493017,8203,9987,2,1,...,59.0,55.0,54.0,72.0,67.0,65.0,70.0,68.0,63.0,Win
1,1,1,2008/2009,25,2009-03-08 00:00:00,493025,9984,8342,1,3,...,66.0,67.0,66.0,70.0,69.0,68.0,67.0,73.0,68.0,Lose
2,1,1,2008/2009,25,2009-03-07 00:00:00,493027,8635,10000,2,0,...,61.0,60.0,49.0,64.0,67.0,66.0,55.0,58.0,64.0,Win
3,1,1,2008/2009,26,2009-03-13 00:00:00,493034,8203,8635,2,1,...,72.0,66.0,67.0,75.0,70.0,74.0,74.0,70.0,69.0,Win
4,1,1,2008/2009,26,2009-03-14 00:00:00,493040,10000,9999,0,0,...,57.0,57.0,51.0,58.0,66.0,57.0,60.0,63.0,65.0,Draw

In [74]:
joined_df.columns

Index(['country_id', 'league_id', 'season', 'stage', 'date', 'match_api_id',
       'home_team_api_id', 'away_team_api_id', 'home_team_goal',
       'away_team_goal', 'home_player_1', 'home_player_2', 'home_player_3',
       'home_player_4', 'home_player_5', 'home_player_6', 'home_player_7',
       'home_player_8', 'home_player_9', 'home_player_10', 'home_player_11',
       'away_player_1', 'away_player_2', 'away_player_3', 'away_player_4',
       'away_player_5', 'away_player_6', 'away_player_7', 'away_player_8',
       'away_player_9', 'away_player_10', 'away_player_11', 'B365H', 'B365D',
       'B365A', 'BWH', 'BWD', 'BWA', 'Winner', 'home_player_1_overall_rating',
       'home_player_2_overall_rating', 'home_player_3_overall_rating',
       'home_player_4_overall_rating', 'home_player_5_overall_rating',
       'home_player_6_overall_rating', 'home_player_7_overall_rating',
       'home_player_8_overall_rating', 'home_player_9_overall_rating',
       'home_player_10_overall_rating', 'home_player_11_overall_rating',
       'away_player_1_overall_rating', 'away_player_2_overall_rating',
       'away_player_3_overall_rating', 'away_player_4_overall_rating',
       'away_player_5_overall_rating', 'away_player_6_overall_rating',
       'away_player_7_overall_rating', 'away_player_8_overall_rating',
       'away_player_9_overall_rating', 'away_player_10_overall_rating',
       'away_player_11_overall_rating', 'Winner2'],
      dtype='object')

In [75]:
cols_of_interest = ['country_id', 'league_id', 'season', 'stage', 'date', 'match_api_id',
       'home_team_api_id', 'away_team_api_id', 'home_team_goal',
       'away_team_goal','B365H', 'B365D','B365A', 'BWH', 'BWD', 'BWA', 'Winner', 'home_player_1_overall_rating',
       'home_player_2_overall_rating', 'home_player_3_overall_rating',
       'home_player_4_overall_rating', 'home_player_5_overall_rating',
       'home_player_6_overall_rating', 'home_player_7_overall_rating',
       'home_player_8_overall_rating', 'home_player_9_overall_rating',
       'home_player_10_overall_rating', 'home_player_11_overall_rating',
       'away_player_1_overall_rating', 'away_player_2_overall_rating',
       'away_player_3_overall_rating', 'away_player_4_overall_rating',
       'away_player_5_overall_rating', 'away_player_6_overall_rating',
       'away_player_7_overall_rating', 'away_player_8_overall_rating',
       'away_player_9_overall_rating', 'away_player_10_overall_rating',
       'away_player_11_overall_rating', 'Winner2']
joined_df = joined_df[cols_of_interest]
joined_df.head()

,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,...,away_player_3_overall_rating,away_player_4_overall_rating,away_player_5_overall_rating,away_player_6_overall_rating,away_player_7_overall_rating,away_player_8_overall_rating,away_player_9_overall_rating,away_player_10_overall_rating,away_player_11_overall_rating,Winner2
0,1,1,2008/2009,24,2009-02-27 00:00:00,493017,8203,9987,2,1,...,59.0,55.0,54.0,72.0,67.0,65.0,70.0,68.0,63.0,Win
1,1,1,2008/2009,25,2009-03-08 00:00:00,493025,9984,8342,1,3,...,66.0,67.0,66.0,70.0,69.0,68.0,67.0,73.0,68.0,Lose
2,1,1,2008/2009,25,2009-03-07 00:00:00,493027,8635,10000,2,0,...,61.0,60.0,49.0,64.0,67.0,66.0,55.0,58.0,64.0,Win
3,1,1,2008/2009,26,2009-03-13 00:00:00,493034,8203,8635,2,1,...,72.0,66.0,67.0,75.0,70.0,74.0,74.0,70.0,69.0,Win
4,1,1,2008/2009,26,2009-03-14 00:00:00,493040,10000,9999,0,0,...,57.0,57.0,51.0,58.0,66.0,57.0,60.0,63.0,65.0,Draw

In [76]:
joined_df.to_csv('FinalDF.csv')

In [82]:
from sklearn import svm
from sklearn.model_selection import train_test_split
features = ['country_id', 'league_id', 'stage', 'match_api_id',
       'home_team_api_id', 'away_team_api_id', 'home_team_goal',
       'away_team_goal','home_player_1_overall_rating',
       'home_player_2_overall_rating', 'home_player_3_overall_rating',
       'home_player_4_overall_rating', 'home_player_5_overall_rating',
       'home_player_6_overall_rating', 'home_player_7_overall_rating',
       'home_player_8_overall_rating', 'home_player_9_overall_rating',
       'home_player_10_overall_rating', 'home_player_11_overall_rating',
       'away_player_1_overall_rating', 'away_player_2_overall_rating',
       'away_player_3_overall_rating', 'away_player_4_overall_rating',
       'away_player_5_overall_rating', 'away_player_6_overall_rating',
       'away_player_7_overall_rating', 'away_player_8_overall_rating',
       'away_player_9_overall_rating', 'away_player_10_overall_rating',
       'away_player_11_overall_rating']
label = ['Winner2']
df_X = joined_df[features]
df_Y = joined_df[label]

X_train, X_test, Y_train, Y_test = train_test_split(df_X, df_Y, test_size=0.33, random_state=42)

In [87]:
model = svm.SVC(kernel='rbf')
model.fit(X_train, Y_train)

c:\users\ayushpc\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\ayushpc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [88]:
from sklearn.metrics import accuracy_score
pred = model.predict(X_test)
accuracy_score(pred, Y_test)

0.4643462190050824

In [90]:
from sklearn import tree
clf2 = tree.DecisionTreeClassifier(criterion='entropy')
clf2.fit(X_train, Y_train)
pred2 = clf2.predict(X_test)
accuracy_score(pred2, Y_test)

0.999691975974126